<?php declare(strict_types = 1);

/**
 * @file
 * Primary module hooks for Foo module.
 */

/**
 * Implements hook_bar_info().
 */
function foo_bar_info(): array {
  return [
    'foo.foo' => [
      'id' => 'foo',
      'label' => t('Foo'),
      'description' => t('Foo description.'),
    ],
    'foo.bar' => [
      'id' => 'bar',
      'label' => t('Bar'),
      'description' => t('Bar description.'),
    ],
  ];
}
