<?php

declare(strict_types=1);

namespace Drupal\Tests\sonata\Unit;

use Composer\Console\Application;
use Drupal\Tests\UnitTestCase;
use Drupal\sonata\Command\ExampleCommand;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Component\Console\Tester\CommandTester;

/**
 * Test generated console command.
 */
#[Group('DCG')]
final class ExampleCommandTest extends UnitTestCase {

  /**
   * Tests callback.
   */
  public function testCommand(): void {
    $application = new Application();
    $application->add(new ExampleCommand());
    $command_tester = new CommandTester(
      $command = $application->get('sonata:example'),
    );
    self::assertSame('sonata:example', $command->getName());
    self::assertSame('Simple command generated by DCG.', $command->getDescription());

    $command_tester->execute(['command' => $command->getName()]);
    self::assertSame(0, $command_tester->getStatusCode());
    self::assertSame('It works!' . \PHP_EOL, $command_tester->getDisplay());
  }

}
