<?php

declare(strict_types=1);

/**
 * @file
 * Install, update and uninstall functions for the Foo module.
 */

/**
 * Implements hook_install().
 */
function foo_install(): void {
  \Drupal::messenger()->addStatus(t('Module Foo has been installed.'));
}

/**
 * Implements hook_uninstall().
 */
function foo_uninstall(): void {
  \Drupal::messenger()->addStatus(t('Module Foo has been uninstalled.'));
}
