<?php

declare(strict_types=1);

/**
 * @file
 * Provides an example entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function foo_theme(): array {
  return [
    'foo_example' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for example templates.
 *
 * Default template: foo-example.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the example information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_foo_example(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function foo_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish examples.
      $storage = \Drupal::entityTypeManager()->getStorage('foo_example');
      $foo_example_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($foo_example_ids) as $foo_example) {
        $foo_example->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize examples.
      $storage = \Drupal::entityTypeManager()->getStorage('foo_example');
      $foo_example_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($foo_example_ids) as $foo_example) {
        $foo_example->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function foo_user_predelete(UserInterface $account): void {
  // Delete examples that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('foo_example');
  $foo_example_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($foo_example_ids)
  );
  // Delete old revisions.
  $foo_example_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($foo_example_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
