<?php declare(strict_types = 1);

namespace PHPSTORM_META {

  registerArgumentsSet('permissions',
    'administer blocks',
    'administer comment types',
    'administer comments',
    'edit own comments',
    'post comments',
    'skip comment approval',
    'access comments',
    'export configuration',
    'import configuration',
    'synchronize configuration',
    'administer contact forms',
    'access site-wide contact form',
    'access user contact forms',
    'access contextual links',
    'edit any basic block content',
    'administer comment display',
    'administer contact_message display',
    'administer node display',
    'administer block_content display',
    'administer taxonomy_term display',
    'administer user display',
    'administer comment fields',
    'administer contact_message fields',
    'administer node fields',
    'administer block_content fields',
    'administer taxonomy_term fields',
    'administer user fields',
    'administer comment form display',
    'administer contact_message form display',
    'administer node form display',
    'administer block_content form display',
    'administer taxonomy_term form display',
    'administer user form display',
    'administer display modes',
    'access files overview',
    'administer filters',
    'use text format basic_html',
    'use text format full_html',
    'use text format restricted_html',
    'administer image styles',
    'create article content',
    'create page content',
    'delete any article content',
    'delete any page content',
    'delete own article content',
    'delete own page content',
    'delete article revisions',
    'delete page revisions',
    'edit any article content',
    'edit any page content',
    'edit own article content',
    'edit own page content',
    'revert article revisions',
    'revert page revisions',
    'view article revisions',
    'view page revisions',
    'access content overview',
    'administer nodes',
    'administer content types',
    'bypass node access',
    'delete all revisions',
    'revert all revisions',
    'view all revisions',
    'view own unpublished content',
    'administer url aliases',
    'create url aliases',
    'administer search',
    'use advanced search',
    'search content',
    'administer shortcuts',
    'customize shortcut links',
    'switch shortcut sets',
    'access shortcuts',
    'administer menu',
    'administer modules',
    'administer site configuration',
    'administer software updates',
    'administer themes',
    'link to any page',
    'access administration pages',
    'access site in maintenance mode',
    'access content',
    'access site reports',
    'view the administration theme',
    'create terms in tags',
    'delete terms in tags',
    'edit terms in tags',
    'access taxonomy overview',
    'administer taxonomy',
    'access toolbar',
    'access tour',
    'view update notifications',
    'administer account settings',
    'administer permissions',
    'administer users',
    'cancel account',
    'change own username',
    'select account cancellation method',
    'view user email addresses',
    'access user profiles',
    'administer views',
  );
  expectedArguments(\Drupal\Core\Session\AccountInterface::hasPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\Core\Access\AccessResult::allowedIfHasPermission(), 1, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::allowedIfHasPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::grantPermission(), 0, argumentsSet('permissions'));
  expectedArguments(\Drupal\user\RoleInterface::revokePermission(), 0, argumentsSet('permissions'));

}
