<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for Example module.
 */

/**
 * Implements hook_theme().
 */
function example_theme(): array {
  return [
    'section' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for section.html.twig template.
 *
 * Default template: section.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_section(array &$variables): void {
  $variables['foo'] = 'bar';
}
