<?php

/**
 * @file
 * Provides an example entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function foo_theme() {
  return [
    'foo_example' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for example templates.
 *
 * Default template: foo-example.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the example information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_foo_example(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
