<?php

/**
 * @file
 * Primary module hooks for Example module.
 */

/**
 * Implements hook_theme().
 */
function example_theme() {
  return [
    'foo' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for foo template.
 *
 * Default template: foo.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_foo(array &$variables) {
  $variables['foo'] = 'foo';
}
